### ISSUE TITLE
PythonInterpreter tcp socket connection error 

### ISSUE THREAD

**Issue by orshih6** [jython/jython#86] opened 2021-03-01 07:46 UTC
im using  pyzk lib. but it is error connection timeout. tcp connection not working

**Comment by jceyca** [comment] 2021-12-29 19:11
Hello Orshih6, do you fix the problem? i have the same problem, i read that the problem is with sockets creation, but i dont found a fix for this.

**Comment by orshih6** [comment] 2022-01-05 05:32
Hello jceyca, no i don't. I changed technology.

**Comment by jeff5** [comment] 2022-04-16 07:57
We would need an example that pinned the blame on Jython to investigate.

**Closed as completed by jeff5** 2022-04-16 07:57 UTC
