### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by thetric** [jython/jython#342] opened 2024-07-18 10:21 UTC
As mentioned in https://github.com/jython/jython/pull/169#issuecomment-1133988745 and https://github.com/jython/jython/pull/157#issuecomment-1132604803 it is preferrable if team members update dependencies:

The following dependencies have later milestone versions:
 - [x] com.github.jnr:jffi [1.3.9 -> 1.3.13]
     http://github.com/jnr/jffi
 - [x] com.github.jnr:jnr-constants [0.10.3 -> 0.10.4]
     http://github.com/jnr/jnr-constants
 - [x] com.github.jnr:jnr-ffi [2.2.12 -> 2.2.16]
     http://github.com/jnr/jnr-ffi
 - [x] com.github.jnr:jnr-posix [3.1.15 -> 3.1.19]
 - [x] com.google.guava:guava [32.1.2-jre -> 33.2.1-jre]
     https://github.com/google/guava
 - [x] com.ibm.icu:icu4j [71.1 -> 75.1]
     https://icu.unicode.org/
 - [x] com.ibm.informix:jdbc [4.50.8 -> 4.50.11]
     https://www.ibm.com/informix
 - [x] com.oracle.database.jdbc:ojdbc8 [19.14.0.0 -> 23.4.0.24.05]
     https://www.oracle.com/database/technologies/maven-central-guide.html
 - [x] commons-io:commons-io [2.15.1 -> 2.16.1]
     https://commons.apache.org/proper/commons-io/
 - [ ] io.netty:netty-buffer [4.1.73.Final -> 4.1.111.Final]
     http://netty.io/
 - [ ] io.netty:netty-codec [4.1.73.Final -> 4.1.111.Final]
     http://netty.io/
 - [ ] io.netty:netty-common [4.1.73.Final -> 4.1.111.Final]
     http://netty.io/
 - [ ] io.netty:netty-handler [4.1.73.Final -> 4.1.111.Final]
     http://netty.io/
 - [ ] io.netty:netty-resolver [4.1.73.Final -> 4.1.111.Final]
     http://netty.io/
 - [ ] io.netty:netty-transport [4.1.73.Final -> 4.1.111.Final]
     http://netty.io/
 - [x] jline:jline [2.14.5 -> 2.14.6]
 - [x] org.antlr:antlr-runtime [3.5.2 -> 3.5.3]
     http://www.antlr.org
 - [x] org.apache.ant:ant [1.10.12 -> 1.10.14]
     https://ant.apache.org/
 - [x] org.apache.commons:commons-compress [1.26.0 -> 1.26.2]
     https://commons.apache.org/proper/commons-compress/
 - [x] org.bouncycastle:bcpkix-jdk18on [1.77 -> 1.78.1]
     https://www.bouncycastle.org/java.html
 - [x] org.bouncycastle:bcprov-jdk18on [1.77 -> 1.78.1]
     https://www.bouncycastle.org/java.html
 - [x] org.ow2.asm:asm [9.6 -> 9.7]
     http://asm.ow2.io/
 - [x] org.ow2.asm:asm-commons [9.6 -> 9.7]
     http://asm.ow2.io/
 - [x] org.ow2.asm:asm-util [9.6 -> 9.7]
     http://asm.ow2.io/

**Comment by Stewori** [comment] 2024-07-19 10:41
I am a bit hesistent to do these updates for 2.7.4 because beta phase is already somewhat through. There will be an rc phase though and these updates are not really changes to Jython. Given the long Jython release cycle, third party libs bundled with 2.7.4 should IMO be indeed as new as possible at release time, especially security-relevant ones like bouncycastle. @jeff5 if you consent I can tackle the third party libs update, but let's agree on a date to avoid repeated effort due to further new releases. My suggestion would be right before rc release (like one day before), to include all updates that pass regrtests. I assume it is okay to take the jars from maven central, because it is an annoying hassle to work through the individual homepages.

**Comment by jeff5** [comment] 2024-07-19 13:14
Left to myself, I'd freeze dependencies at the beta. I did a round of updating then, but beta phase has run on a bit. I think accepting dependency changes into a release candidate, on condition they don't create a regression is a fair suggestion. If we have to make code changes of our own to adjust to them, that's a beta.

@thetric thanks for the comprehensive list. I know I tried to advance a few of of these at b1, and they caused problems. I can see I tried netty 4.1.80 and rejected it.

We don't bundle the Oracle and Informix JARs, but of course we specify versions.

**Comment by Stewori** [comment] 2024-07-19 14:24
Thanks, @jeff5 for the clarification. I was not aware that a netty update would cause problems (perhaps you pointed it out somewhere but I forgot or overlooked). Perhaps it would be good to directly open issues for such failures to keep track (may be a "won't fix", that would also be fine, but it should be tracked).

**Comment by jeff5** [comment] 2024-07-19 17:13
I would have said I'd noted it in the build files, but not when I look. (Maybe on a branch I dropped.)

**Comment by jeff5** [comment] 2024-07-20 15:19
I'll work through these and see how they treat us.

**Comment by jeff5** [comment] 2024-07-21 08:04
JARs for jdbc and ojdbc are citations in our build, but not bundled.

Ant is used in the build (including for a custom plug-in) but not bundled.

**Comment by Stewori** [comment] 2024-07-21 12:18
Not bundling ant appears a bit dubious to me, because I get plenty of missing symbol and missing package errors if ant is not on the classpath, e.g. like this one:
```
.../jython/2.7.3/src/org/python/util/GlobMatchingTask.java:12: error: cannot find symbol
public abstract class GlobMatchingTask extends MatchingTask {
                                               ^
  symbol: class MatchingTask
```
This does not look like code that can never execute on runtime, does it?

See `org.apache.tools.ant` occurring in the imports of
[ExposeTask](https://apidia.net/java/Jython/2.7.3/?pck=org.python.expose.generate&cls=.ExposeTask)
[GlobMatchingTask](https://apidia.net/java/Jython/2.7.3/?pck=org.python.util&cls=.GlobMatchingTask)
[JythoncAntTask](https://apidia.net/java/Jython/2.7.3/?pck=org.python.util&cls=.JythoncAntTask)
[JycompileAntTask](https://apidia.net/java/Jython/2.7.3/?pck=org.python.util&cls=.JycompileAntTask)

Maybe the `org.python.util` package needs some cleanup (for the runtime distribution). No need to handle this now before the release, but maybe we should track it in an issue. `JythoncAnTask` is probably obsolete and I agree that `JycompileAntTask` sounds like only build-time. But `ExposeTask`?

**Comment by jeff5** [comment] 2024-07-21 21:37
> Not bundling ant appears a bit dubious to me

I believe it is what this is about: https://github.com/jython/jython/blob/82bd1178902933f95f2d23e1e6efa118548d454a/build.xml#L750 although it is only there to compile the custom Ant tasks. `ExposeTask` processes Java classes and `JycompileAntTask` compiles the stdlib.

Ideally, build tools would be in a separate tree, not mixed in with the delivered code, and filtered out later. https://github.com/jython/jython/blob/82bd1178902933f95f2d23e1e6efa118548d454a/build.xml#L982

**Comment by Stewori** [comment] 2024-07-21 22:34
After some reading on the topic I learned that it is quite more usual for Java programs/libs to omit dependencies as "compile-time only" than I thought. Seemingly, there is no systematic/general/reliable/automatic way to decide which libs are runtime dependencies and which are not (I know, the dependencies in pom files may indicate the dependency types, but I found it unreliable, at least for determining compile-time dependencies). So it's often a bit dubious, perhaps dependent on the use case, and some unfortunate user may still find a way to use a lib such that a missing runtime-lib/thought-to-be compile-time lib crashes the thing. (but of course you know all this)
Given that issue, I suppose some cleanup would be good. What can safely be sorted out should be, to minimize the issue at least.
>  build tools would be in a separate tree, not mixed in with the delivered code

Yes, that's also my thinking. Probably, the first step would be to move everything ant-dependent out of `org.python.util` into a new folder and package, e.g. `org.python.ant` which can then be added to `excludes` in `build.xml`. Perhaps, we can attempt that refactoring for 2.7.5. Would be good to have the separation for Jython 3 at least. Can Java modularization be of any help for that? (Note: For Java modularization compile-time-only dependencies are referenced as `requires static`.) Or maybe the problem is obsolete in Gradle.

**Comment by jeff5** [comment] 2024-07-22 18:24
My appetite for improvements to Jython 2 is limited. I looked into the Ant plug-ins for a few hours and decided to leave them alone.

I'm writing from knowledge of Jython 3 (or VSJ) and struggling with Gradle, which has a specific feature for tool-building before the build proper. Done right, it should cut down the build time by recognising when artefacts are up to date. I made it work once in Java, but I can't figure it out when the tool is in Python. I've spent more time trying than it will ever save.

> Or maybe the problem is obsolete in Gradle.

No. It needs you to tell it, but how you do that makes reasonable sense.

**Comment by jeff5** [comment] 2024-07-22 18:34
I tried updating Netty to 4.1.112, but it gives me errors in `test_httplib` and `test_ssl_jy`. The error is always:
```
SSLError: [Errno 1] SslHandler removed before handshake completed
```
I smell concurrency/async, which is Netty's selling point, but I believe we do not need it for the library and have not used it correctly.

**Comment by Stewori** [comment] 2024-07-22 19:55
> No. It needs you to tell it,

At least there won't be AntTasks.

**Comment by jeff5** [comment] 2024-07-28 12:21
I think we have updated all we can in response to this, so it looks like we have an rc1. @Stewori : am I missing something you really wanted to be in?

**Comment by Stewori** [comment] 2024-07-29 13:23
Thank you Jeff, for all this work. I have nothing more to add here. The Netty situation is not ideal, but apparently not solvable in short term. So, feel free to proceed!

**Comment by jeff5** [comment] 2024-08-02 06:10
As the Netty shortfall is documented in #349 I'll close this.

**Closed as completed by jeff5** 2024-08-02 06:10 UTC
